SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_SYSROOT "${CONAN_USER_GCC_8.5.0_GLIBC_2.27_X86_64_SYSROOT}")
SET(CMAKE_C_COMPILER   ${CONAN_USER_GCC_8.5.0_GLIBC_2.27_X86_64_C_COMPILER})
SET(CMAKE_CXX_COMPILER ${CONAN_USER_GCC_8.5.0_GLIBC_2.27_X86_64_CXX_COMPILER})

SET(CMAKE_C_FLAGS   "-fPIC            -O0 -ggdb -Wall -rdynamic -Wno-unused-variable -Wno-unused-value -fvisibility=hidden -rdynamic" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS "-fPIC -std=c++11 -O0 -ggdb -Wall -rdynamic -Wno-unused-variable -Wno-unused-value -fvisibility=hidden -rdynamic" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
